logging:
  log_level: "DEBUG"            # DEBUG > INFO > WARN > ERROR                                                  ; default: DEBUG

mqtt:
  enable: false                 #                                                                              ; default: false
  broker_address: "localhost"   #                                                                              ; default: localhost
  broker_port: 1883             #                                                                              ; default: 1883
  topic: 
    - "example/topic"           #                                                                              ; default: example/topic
  keep_alive: 60s               # seconds                                                                      ; default: 60s
  reconnect_interval: 10s       # seconds                                                                      ; default: 10s
  auto_reconnect: true          #                                                                              ; default: true
  device_name: "example"        #                                                                              ; default: example
  username: ""                  # optional                                                                     ; default: none
  password: ""                  # optional                                                                     ; default: none

spi:
  enable: false                 # Control ALL SPI buses                                                        ; default: false
  device:       
    spi0:
      enable: false             # Control single (this) SPI bus                                                ; default: false
      name: 0                   # 0 == /dev/spidev0.0                                                          ; default: 0
      speed: 10_000_000         # 10 MHz                                                                       ; default: 10_000_000 (Hz)
      mode: 0                   # 0 - CPOL=0,CPHA=0 ; 1 - CPOL=0,CPHA=1 ; 2 - CPOL=1,CPHA=0 ; 3 CPOL=1,CPHA=1  ; default: 0
      bits_per_word: 8          #                                                                              ; default: 8
    spi1:
      enable: false
      name: 1
      speed: 10_000_000
      mode: 0    
      bits_per_word: 8        

i2c:
  enable: false                 # Control ALL I2C buses                                                        ; default: false
  device:
    i2c0:
      enable: false             # Control single (this) I2C bus                                                ; default: false
      name: 0                   # 0 == /dev/i2c-0
    i2c1:
      enable: false
      name: 1
  
uart:
  enable: false                 # Control ALL UART buses                                                       ; default: false
  device:
    uart0:
      enable: false             # Control single (this) UART bus                                               ; default: false
      name: 0                   # 0 == /dev/ttyAMA0
      speed: 9600               # Baud rate
      data_length: 8            # Bits per packet                                                              ; default: 8
      parity_bit: "N"           # N - None ; O - 1 when odd ; E - 1 when even ; M - 1 ; S - 0                  ; default: N
      stop_bit: 1               # 1 - 1 ; 15 - 1.5 ; 2 - 2                                                     ; default: 1 
      data_flow: 0              # 0 - no flow ; 1 - XOn/XOff ; 2 - RTSCTS                                      ; default: 0
    uart1:
      enable: false
      name: 1
      speed: 9600
      data_length: 8
      parity_bit: "N"
      stop_bit: 1
      data_flow: 0  

onewire:
  enable: false                 # Control ALL 1W buses                                                         ; default: false
  device:
    ow0:
      enable: true              # Control single (this) 1W bus                                                 ; default: false
      name: 1                   # 1 == /sys/bus/w1/devices/w1_bus_master1
    ow1:
      enable: false
      name: 2                   

lora:
  enable: false                 #                                                                              ; default: false
  modem: "lora"                 # lora / fsk                                                                   ; default: lora
  type: "1262"                  # 1261 / 1262                                                                  ; default: 1262
  bandwidth: 125_000            # 125 kHz                                                                      ; default: 125_000 (Hz)
  spreding_factor: 7            # 7 - 12                                                                       ; default: 7
  coding_rate: 5                # (FSK only: 4 - 4/4) ; 5 - 4/5 ; 6 - 4/6 ; 7 - 4/7 ; 8 - 4/8                  ; default: 5
  ldro: false                   # Low Data Rate Optimize                                                       ; default: false
  dc_dc: false                  # Internal DC-DC converter                                                     ; default: false
  header_implicit: false        # false - explicit ; true - implicit                                           ; default: false (aka explicit)
  frequency: 433_000_000        # 433 MHz                                                                      ; default: 433_000_000 (Hz)
  preamble_length: 12           # Symbols (time(ms) = len*(2^sf/bw(kHz))+4.25)                                 ; default: 12 (16.5 ms)
  payload_length: 32            # Bytes (MTU)                                                                  ; default: 32
  crc: true                     # Error correction                                                             ; default: true
  inverted_iq: false            # false - standard ; true - inverted                                           ; default: false
  sync_word: 0x1424             # 0x1424 - private network ; 0x3444 - public network                           ; default: 0x1424
  tx_power: 0                   # -12 - +22 dBm                                                                ; default: 0 (dBm)
  standby_mode: "rc"            # rc / xosc                                                                    ; default: rc
  sleep_mode: "warm_start"      # cold_start ; warm_start ; cold_start_rtc ; warm_start_rtc                    ; default: cold_start
  frequency_range:              # 430-440 ; 470-510 ; 779-787 ; 863-870 ; 902-928                              ; default: 430-440 (MHz)  
    - 430
    - 440
  ramp_time: 800                # 10 - 3400 us                                                                 ; default: 800 (us)
  dio2_as_rf_switch: true       # Configure DIO2 so that it can be used to control an external RF switch       ; default: true
  rx_queue_size: 10             # Size of byte array channel                                                   ; default: 10
  tx_queue:size: 10             # Size of byte array channel                                                   ; default: 10
  rx_buffer_address: 128        # Start address of RX buffer (0-255)                                           ; default: 128
  tx_buffer_address: 0          # Start address of TX buffer (0-255)                                           ; default: 0
  tx_timeout: 0                 # Timeout * 15.625 us (0 to disable)                                           ; default: 0
  pins:
    reset: "GPIO18"             #                                                                              ; default: GPIO18
    busy: "GPIO20"              #                                                                              ; default: GPIO20
    dio: "GPIO16"               #                                                                              ; default: GPIO16
    tx_enable: "GPIO6"          #                                                                              ; default: GPIO6
    rx_enable: ""               #                                                                              ; default: none
    cs: "GPIO21"                #                                                                              ; default: GPIO21
  cad:
    symbol_number: 2            # 1 - 16 symbols                                                               ; default: 2 (2 == 2^2 symbols)
    detection_peak: 20          # 18 - 25                                                                      ; default: 20 (20 for SF7)
    detection_minimum: 10       # Should always be 10 for SX126x                                               ; default: 10 (10 for SF7)
    exit_mode: 0                #                                                                              ; default: 0
    timeout: 0                  # 0 - no timeout                                                               ; default: 0